const dummyData = {
  ids: [1, 2, 3, 4, 5, 6, 7, 8],
  characters: {
    1: {
      id: 1,
      name: 'Luke Skywalker',
      gender: 'male',
      skinColor: 'fair',
      hairColor: 'blond',
      height: 172,
      eyeColor: 'blue',
      mass: 77,
      birthYear: '19BBY',
    },
    2: {
      id: 2,
      name: 'C-3PO',
      gender: 'n/a',
      skinColor: 'gold',
      hairColor: 'n/a',
      height: 167,
      eyeColor: 'yellow',
      mass: 75,
      birthYear: '112BBY',
    },
    3: {
      id: 3,
      name: 'R2-D2',
      gender: 'n/a',
      skinColor: 'white, blue',
      hairColor: 'n/a',
      height: 96,
      eyeColor: 'red',
      mass: 32,
      birthYear: '33BBY',
    },
    4: {
      id: 4,
      name: 'Darth Vader',
      gender: 'male',
      skinColor: 'white',
      hairColor: 'none',
      height: 202,
      eyeColor: 'yellow',
      mass: 136,
      birthYear: '41.9BBY',
    },
    5: {
      id: 5,
      name: 'Leia Organa',
      gender: 'female',
      skinColor: 'light',
      hairColor: 'brown',
      height: 150,
      eyeColor: 'brown',
      mass: 49,
      birthYear: '19BBY',
    },
    6: {
      id: 6,
      name: 'Owen Lars',
      gender: 'male',
      skinColor: 'light',
      hairColor: 'brown, grey',
      height: 178,
      eyeColor: 'blue',
      mass: 120,
      birthYear: '52BBY',
    },
    7: {
      id: 7,
      name: 'Beru Whitesun lars',
      gender: 'female',
      skinColor: 'light',
      hairColor: 'brown',
      height: 165,
      eyeColor: 'blue',
      mass: 75,
      birthYear: '47BBY',
    },
    8: {
      id: 8,
      name: 'R5-D4',
      gender: 'n/a',
      skinColor: 'white, red',
      hairColor: 'n/a',
      height: 97,
      eyeColor: 'red',
      mass: 32,
      birthYear: null,
    },
  },
};

export default dummyData;
