const dummyData = [
  {
    id: 1,
    name: 'Luke Skywalker',
    gender: 'male',
    skin_color: 'fair',
    hair_color: 'blond',
    height: 172,
    eye_color: 'blue',
    mass: 77,
    birth_year: '19BBY',
  },
  {
    id: 2,
    name: 'C-3PO',
    gender: 'n/a',
    skin_color: 'gold',
    hair_color: 'n/a',
    height: 167,
    eye_color: 'yellow',
    mass: 75,
    birth_year: '112BBY',
  },
  {
    id: 3,
    name: 'R2-D2',
    gender: 'n/a',
    skin_color: 'white, blue',
    hair_color: 'n/a',
    height: 96,
    eye_color: 'red',
    mass: 32,
    birth_year: '33BBY',
  },
  {
    id: 4,
    name: 'Darth Vader',
    gender: 'male',
    skin_color: 'white',
    hair_color: 'none',
    height: 202,
    eye_color: 'yellow',
    mass: 136,
    birth_year: '41.9BBY',
  },
  {
    id: 5,
    name: 'Leia Organa',
    gender: 'female',
    skin_color: 'light',
    hair_color: 'brown',
    height: 150,
    eye_color: 'brown',
    mass: 49,
    birth_year: '19BBY',
  },
  {
    id: 6,
    name: 'Owen Lars',
    gender: 'male',
    skin_color: 'light',
    hair_color: 'brown, grey',
    height: 178,
    eye_color: 'blue',
    mass: 120,
    birth_year: '52BBY',
  },
  {
    id: 7,
    name: 'Beru Whitesun lars',
    gender: 'female',
    skin_color: 'light',
    hair_color: 'brown',
    height: 165,
    eye_color: 'blue',
    mass: 75,
    birth_year: '47BBY',
  },
  {
    id: 8,
    name: 'R5-D4',
    gender: 'n/a',
    skin_color: 'white, red',
    hair_color: 'n/a',
    height: 97,
    eye_color: 'red',
    mass: 32,
    birth_year: null,
  },
];

export default dummyData;
